language: go
<<<<<<< HEAD
go_import_path: github.com/teslafunds/go-teslafunds
=======
go_import_path: github.com/dubaicoin-dbix/go-dubaicoin
>>>>>>> 7fdd714... gdbix-update v1.5.0
sudo: false
matrix:
  include:
    - os: linux
      dist: trusty
<<<<<<< HEAD
      go: 1.4.2
    - os: linux
      dist: trusty
      go: 1.5.4
    - os: linux
      dist: trusty
      go: 1.6.2
    - os: osx
      go: 1.6.2

    # This builder does the PPA upload (and nothing else).
    - os: linux
      dist: trusty
      go: 1.6.2
      env: PPA
=======
      go: 1.5.4
      env:
        - GO15VENDOREXPERIMENT=1
    - os: linux
      dist: trusty
      go: 1.6.2
    - os: linux
      dist: trusty
      go: 1.7.4
    - os: osx
      go: 1.7.4

    # This builder does the Ubuntu PPA and Linux Azure uploads
    - os: linux
      dist: trusty
      sudo: required
      go: 1.7.4
      env:
        - ubuntu-ppa
        - azure-linux
>>>>>>> 7fdd714... gdbix-update v1.5.0
      addons:
        apt:
          packages:
            - devscripts
            - debhelper
            - dput
<<<<<<< HEAD
      script:
        - go run build/ci.go travis-debsrc

=======
            - gcc-multilib
      script:
        # Build for the primary platforms that Trusty can manage
        - go run build/ci.go debsrc -signer "Go Ethereum Linux Builder <geth-ci@ethereum.org>" -upload ppa:ethereum/ethereum
        - go run build/ci.go install
        - go run build/ci.go archive -type tar -signer LINUX_SIGNING_KEY -upload gethstore/builds
        - go run build/ci.go install -arch 386
        - go run build/ci.go archive -arch 386 -type tar -signer LINUX_SIGNING_KEY -upload gethstore/builds

        # Switch over GCC to cross compilation (breaks 386, hence why do it here only)
        - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-arm-linux-gnueabi libc6-dev-armel-cross gcc-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-aarch64-linux-gnu libc6-dev-arm64-cross
        - sudo ln -s /usr/include/asm-generic /usr/include/asm

        - GOARM=5 CC=arm-linux-gnueabi-gcc go run build/ci.go install -arch arm
        - GOARM=5 go run build/ci.go archive -arch arm -type tar -signer LINUX_SIGNING_KEY -upload gethstore/builds
        - GOARM=6 CC=arm-linux-gnueabi-gcc go run build/ci.go install -arch arm
        - GOARM=6 go run build/ci.go archive -arch arm -type tar -signer LINUX_SIGNING_KEY -upload gethstore/builds
        - GOARM=7 CC=arm-linux-gnueabihf-gcc go run build/ci.go install -arch arm
        - GOARM=7 go run build/ci.go archive -arch arm -type tar -signer LINUX_SIGNING_KEY -upload gethstore/builds
        - CC=aarch64-linux-gnu-gcc go run build/ci.go install -arch arm64
        - go run build/ci.go archive -arch arm64 -type tar -signer LINUX_SIGNING_KEY -upload gethstore/builds

    # This builder does the OSX Azure, Android Maven and Azure and iOS CocoaPods and Azure uploads
    - os: osx
      go: 1.7.4
      env:
        - azure-osx
        - mobile
      script:
        - go run build/ci.go install
        - go run build/ci.go archive -type tar -signer OSX_SIGNING_KEY -upload gethstore/builds

        # Build the Android archive and upload it to Maven Central and Azure
        - brew update
        - travis_wait 60 brew install android-sdk android-ndk maven gpg
        - alias gpg="gpg2"

        - export ANDROID_HOME=/usr/local/opt/android-sdk
        - export ANDROID_NDK=/usr/local/opt/android-ndk
        - echo "y" | android update sdk --no-ui --filter `android list sdk | grep "SDK Platform Android" | grep -E 'API 15|API 19|API 24' | awk '{print $1}' | cut -d '-' -f 1 | tr '\n' ','`

        - go run build/ci.go aar -signer ANDROID_SIGNING_KEY -deploy https://oss.sonatype.org -upload gethstore/builds

        # Build the iOS framework and upload it to CocoaPods and Azure
        - gem uninstall cocoapods -a
        - gem install cocoapods --pre

        - mv ~/.cocoapods/repos/master ~/.cocoapods/repos/master.bak
        - sed -i '.bak' 's/repo.join/!repo.join/g' $(dirname `gem which cocoapods`)/cocoapods/sources_manager.rb
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git clone --depth=1 https://github.com/CocoaPods/Specs.git ~/.cocoapods/repos/master && pod setup --verbose; fi

        - xctool -version
        - xcrun simctl list

        - go run build/ci.go xcode -signer IOS_SIGNING_KEY -deploy trunk -upload gethstore/builds
>>>>>>> 7fdd714... gdbix-update v1.5.0

install:
  - go get golang.org/x/tools/cmd/cover
script:
  - go run build/ci.go install
<<<<<<< HEAD
  - go run build/ci.go test -coverage -vet
after_success:
  # - go run build/ci.go archive -type tar
=======
  - go run build/ci.go test -coverage -vet -misspell
>>>>>>> 7fdd714... gdbix-update v1.5.0

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e09ccdce1048c5e03445
    on_success: change
    on_failure: always
